### ISSUE TITLE
PostgreSQL tests fail

### ISSUE THREAD

**Issue by ju5t** [sensson/puppet-powerdns#80]
I just noticed tests fail for PostgreSQL. We don't use PostgreSQL so if anyone can help out that would be great.

**Comment by brigriffin** [comment]
I would like to have a look at this, do you have the logs of the failing tests somewhere?

**Comment by ju5t** [comment]
As it turns out this isn't the only failure. There is an issue with `yum-plugin-priorities` also. Both are on CentOS 8. The `yum-plugin-priorities` should be an easy fix I can probably look into tomorrow.

```
4) powerdns supported operating systems on centos-8-x86_64 powerdns class with postgresql backend is expected to contain Postgresql::Server::Db[powerdns] with user => "foo"
     Failure/Error: fail('No preferred version defined or automatically detected.')
     
     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, No preferred version defined or automatically detected. at /home/travis/build/sensson/puppet-powerdns/spec/fixtures/modules/postgresql/manifests/globals.pp:135:5 on node travis-job-f15e0f9f-5d29-4d93-9328-7262abe59c3e.c.travis-ci-prod-oss-4.internal
```

**Comment by brigriffin** [comment]
Looks like the PostgreSQL default or preferred version as they call it and as defined in default_version (see https://github.com/puppetlabs/puppetlabs-postgresql/blob/main/manifests/globals.pp#L160) could not be detected for CentOS 8. 

Do you maybe by chance have the output of the puppet facter for ['os']['family'], ['os']['name'] and ['os']['release']['full'] for this CentOS 8 test on travis? Ideally it should match an entry from the default_version but it seems that CentOS is missing there. You can see the facter facts by running the `facter` command.

**Comment by ju5t** [comment]
My local ruby environment is broken. I'm guessing this is an issue with `rspec-puppet-facts`. This is where all facts should be coming from:

In `spec_helper.rb` we got:

```ruby
require 'rspec-puppet-facts'

include RspecPuppetFacts
```

Perhaps an upgrade would be all, but I can't test that right now because ruby let me down on my machine.

**Comment by brigriffin** [comment]
You probably are right with the `rspec-puppet-facts` being out of date. I checked and currently 1.9.x which is fron 2018-19 is used:

https://github.com/sensson/puppet-powerdns/blob/186bed4595da5a874e64b8bee37dc0d803b6b84b/Gemfile#L10

There is a newer version 2 out since this year. Before simply bumping this gem dependency to 2.x or at least to 1.10.x I would like to test but unfortunately the puppet-powerdns module requires Ruby 2.3 which is EOL since 2019. I can't even run Ruby 2.3 on my computer (Debian 10) as it requires an outdated OpenSSL library.

Is there any reasons why this module still uses Ruby 2.3?

**Comment by ju5t** [comment]
> Is there any reasons why this module still uses Ruby 2.3?

No, it's a legacy thing and is only required for testing. Feel free to bump where needed.
