### ISSUE TITLE
sqlite parameta for shemata missing, presetting is wrong

### ISSUE THREAD

**Issue by LooOOooM** [sensson/puppet-powerdns#97]
the predefined parameter "$sqlite_schema_file" in case of redhat family is  wrong. it should be called: '/usr/share/doc/pdns-backend-sqlite-4.?.?/schema.sqlite3.sql' rather then '/usr/share/doc/pdns-backend-sqlite-4.?.?/schema.sqlite.sql'.

In addition is not possible to change this var as the class powerdns is missing the line in () where we could change this.

**Comment by LooOOooM** [comment]
ping ...

**Comment by ju5t** [comment]
@LooOOooM you do know that this is very unfriendly behaviour in any open source project, right? This is a project where we spend our free time on. It's not commercial, nobody earns anything or gets paid to make this.

We appreciate your work, but pinging or asking for updates is something we do not want to see in our projects.

We will be releasing this. I can't tell you when. For now, I will be closing this issue.

**Comment by ju5t** [comment]
@LooOOooM I am going to reopen this. Not because it hasn't been merged, but because it's probably not fixed 100%.

Which OS have you checked this on? The check in `params.pp` is for the OS family RedHat, this includes RedHat itself and CentOS (and probably others in the future). I did a check on CentOS 7 & 8:

- On CentOS 8 the file is here: `/usr/share/doc/pdns-backend-sqlite/schema.sqlite3.sql`. This is a different path.
- On CentOS 7 the file doesn't exist at all.

If this is going to be fixed, it needs to be fixed for those operating systems too. This means:

- The params.pp file path should be adjusted for CentOS 8 (I know this will be EOL by the end of the year, but other operating systems will take over and are likely to have the same location).
- Creating tables should throw an error if the file is not set or the file does not exist.

If you do decide to fix this, please open a new PR in a new branch and PR it to our develop branch. Don't reuse your old branch as it will cause issues.

**Comment by LooOOooM** [comment]
#cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
-------
# rpm -qa|grep pdns
pdns-backend-sqlite-4.5.0-0.alpha0.master.928.g2b3dbbb61.1pdns.el7.x86_64
pdns-recursor-4.5.0-0.alpha3.master.105.g2b3dbbb61.1pdns.el7.x86_64
pdns-4.5.0-0.alpha0.master.928.g2b3dbbb61.1pdns.el7.x86_64
-------
#rpm -ql pdns-backend-sqlite-4.5.0-0.alpha0.master.928.g2b3dbbb61.1pdns.el7.x86_64|grep "\/schema.sqlite3.sql"
/usr/share/doc/pdns-backend-sqlite-4.5.0/schema.sqlite3.sql
---------------------------------
---------------------------------
# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)
-----
# rpm -qa|grep pdns
pdns-backend-sqlite-4.5.0-0.alpha0.master.1020.g84808ff64.1pdns.el8.x86_64
pdns-recursor-4.5.0-0.beta1.master.11.g84808ff64.1pdns.el8.x86_64
pdns-4.5.0-0.alpha0.master.1020.g84808ff64.1pdns.el8.x86_64
-----
#  rpm -ql pdns-backend-sqlite-4.5.0-0.alpha0.master.1020.g84808ff64.1pdns.el8.x86_64|grep "\/sche"
/usr/share/doc/pdns-backend-sqlite/schema.sqlite3.sql

-----------------------------------------
-----------------------------------------

**Comment by ju5t** [comment]
This is locked. If someone runs into this issue and can create a PR that solves it properly and fully, please do.
